name: Workflow

on:
  push:
    branches:
      - "main"
      - "feature/listcodeapplications"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Calculate gitVersion
        id: gitVersion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v4.5
        with:
          modules-to-cache: Microsoft.PowerShell.Crescendo

      - name: Compile Crescendo Module
        run: |
          . .\OutputHandlers\parseExtension.ps1
           Export-CrescendoModule -ConfigurationFile "vscodeinsiders.crescendo.config.json -ModuleName "VSCodeInsiders"
        shell: pwsh
